module: CatalogByConvention
module_version: 1.0.0
umbrella_header: src/CatalogByConvention.h
objc: true
sdk: iphonesimulator
github_url: https://github.com/material-foundation/cocoapods-catalog-by-convention
github_file_prefix: https://github.com/material-foundation/cocoapods-catalog-by-convention/tree/v2.0.0
